name: Build 64-bit Natives

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - '*'

jobs:
  build-natives:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download llvm-mingw
        uses: robinraju/release-downloader@v1.10
        with:
          repository: 'mstorsjo/llvm-mingw'
          tag: 20240619
          fileName: llvm-mingw-20240619-ucrt-ubuntu-20.04-x86_64.tar.xz

      - name: Set up llvm-mingw
        run: |
          sudo mkdir -p /usr/local
          sudo tar -Jxf llvm-mingw-20240619-ucrt-ubuntu-20.04-x86_64.tar.xz -C /usr/local
          echo "PATH=/usr/local/llvm-mingw-20240619-ucrt-ubuntu-20.04-x86_64/bin:$PATH" >> $GITHUB_ENV

      - name: Install Linux toolchains
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc g++

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Linux64 and Windows64
        run: |
          ./gradlew jniGen
          ./gradlew jnigenBuildLinux64
          ./gradlew jnigenBuildWindows64

      - name: Upload 64-bit natives
        uses: actions/upload-artifact@v4
        with:
          name: 64bit-natives
          path: ./*/libs
          retention-days: 7
